<a href="https://colab.research.google.com/github/03dipak/INSAIDCapstone1/blob/master/capstone1060.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Insaid Telecom Project***

**Submitted by Group 1060**

In [0]:
Index

1. Bu
2. Data Description

****1. About Company****

InsaidTelecom, one of the leading telecom players, understands that customizing offering is very important for its business to stay competitive. 

Currently, InsaidTelecom is seeking to leverage behavioral data from more than **60% of the 50 million mobile devices** active daily in India
to help its clients better understand and interact with their audiences.

Insaidians are expected to **build a dashboard** to **understand user's demographic characteristics based on their mobile usage, geolocation, and mobile device properties**.

Doing so will help millions of developers and brand advertisers around the world **pursue data-driven marketing efforts** which are relevant to their 
users and catered to their preferences.

**1.1 Goals**

- Have depth of clarity in the underlying data. 

- Cleansing and purify the data

- Submit report on the detailed observation about data

**1.2 Objectives**

- Finding user behavior which is going to directly impact the company's offerings.

- Suggest actionable insights from marketing and product terms.

###2. Data Description

The Data is collected from mobile apps that use InsaidTelecom services. 

The data schema can be represented in the following table:

**gender_age_train** - Devices and their respective user gender, age and age_group

**phone_brand_device_model** - device ids, brand, and models phone_brand ( few brands are in Chinese)

**events_data** - when a user uses mobile on INSAID Telecom network, the event gets logged in this data.
Each event has an event id, location (lat/long), and the event corresponds to frequency of mobile usage. timestamp: when the user is using the mobile.

**Installing My SQL connector package**

In [0]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.6/dist-packages (8.0.19)
Requirement already satisfied: protobuf==3.6.1 in /usr/local/lib/python3.6/dist-packages (from mysql-connector-python) (3.6.1)
Requirement already satisfied: dnspython==1.16.0 in /usr/local/lib/python3.6/dist-packages (from mysql-connector-python) (1.16.0)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.6/dist-packages (from protobuf==3.6.1->mysql-connector-python) (1.12.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf==3.6.1->mysql-connector-python) (45.2.0)

**Importing all required Package**

In [0]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas_profiling

import plotly.offline as py
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
from plotly import tools

import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore",category=DeprecationWarning)

In [0]:
import mysql.connector as ms

cnx = ms.connect(host='cpanel.insaid.co',user='student', password='student',database='Capstone1')
cursor = cnx.cursor()

cursor.execute("SHOW TABLES")

tables = cursor.fetchall() ## it returns list of tables present in the database

## showing all the tables one by one
for table in tables:
    print(table)

('events_data',)
('gender_age_train',)
('phone_brand_device_model',)

**Gender Age Table**

In [0]:
sql_select_Query = ("select * from gender_age_train")
cursor.execute(sql_select_Query)
print(cursor)
gender_age_data=cursor.fetchall()
print(gender_age_data[0])

CMySQLCursor: select * from gender_age_train
(-8076087639492063270, 'M', 35, 'M32-38')

In [0]:
gender_age_df = pd.DataFrame(gender_age_data)
column_names = [i[0] for i in cursor.description]

gender_age_df.columns = column_names
len(gender_age_df)

74645

In [0]:
gender_age_df.to_csv("gender_age.csv")
gender_age_df.columns

Index(['device_id', 'gender', 'age', 'group'], dtype='object')

In [0]:
gender_age_df.head()

             device_id gender  age   group
0 -8076087639492063270      M   35  M32-38
1 -2897161552818060146      M   35  M32-38
2 -8260683887967679142      M   35  M32-38
3 -4938849341048082022      M   30  M29-31
4   245133531816851882      M   30  M29-31

In [0]:
gender_age_df.dtypes

device_id     int64
gender       object
age           int64
group        object
dtype: object

In [0]:
gender_age_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74645 entries, 0 to 74644
Data columns (total 4 columns):
device_id    74645 non-null int64
gender       74645 non-null object
age          74645 non-null int64
group        74645 non-null object
dtypes: int64(2), object(2)
memory usage: 2.3+ MB

In [0]:
gender_age_df.describe()

          device_id           age
count  7.464500e+04  74645.000000
mean  -7.491354e+14     31.410342
std    5.327150e+18      9.868735
min   -9.223067e+18      1.000000
25%   -4.617367e+18     25.000000
50%   -1.841362e+16     29.000000
75%    4.636656e+18     36.000000
max    9.222849e+18     96.000000

In [0]:
gender_age_df.group.unique()

array(['M32-38', 'M29-31', 'F24-26', 'F33-42', 'F27-28', 'M39+', 'M23-26',
       'M27-28', 'M22-', 'F43+', 'F23-', 'F29-32'], dtype=object)

In [0]:
gender_age_df.group.value_counts()

M23-26    9605
M32-38    9476
M39+      8581
M22-      7488
M29-31    7309
F33-42    5561
M27-28    5445
F23-      5050
F29-32    4628
F43+      4194
F24-26    4190
F27-28    3118
Name: group, dtype: int64

In [0]:
gender_age_df.nunique(axis=0) #returns the number of unique values for each variable.

device_id    74645
gender           2
age             85
group           12
dtype: int64

In [0]:
gender_age_df['group'].value_counts().plot.bar(title='Freq dist of group Type')

In [0]:
gender_age_df['gender'].value_counts().plot.bar(title='Gender wise device distribution')



**Phone brand device Table**

In [0]:
device_select_Query = ("select * from phone_brand_device_model")
cursor.execute(device_select_Query)
print(cursor)
phone_brand_device=cursor.fetchall()
print(phone_brand_device[0])

CMySQLCursor: select * from phone_brand_device_model
(1877775838486905855, 'vivo', 'Y13')

In [0]:
phone_brand_df = pd.DataFrame(phone_brand_device)
column_names = [i[0] for i in cursor.description]

phone_brand_df.columns = column_names
len(phone_brand_df)

87726

In [0]:
phone_brand_df.to_csv("phone_brand.csv")
phone_brand_df.columns

Index(['device_id', 'phone_brand', 'device_model'], dtype='object')

In [0]:
phone_brand_df.head()

             device_id phone_brand device_model
0  1877775838486905855        vivo          Y13
1 -3766087376657242966          小米         V183
2 -6238937574958215831        OPPO          R7s
3  8973197758510677470          三星        A368t
4 -2015528097870762664          小米      红米Note2

In [0]:
phone_brand_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87726 entries, 0 to 87725
Data columns (total 3 columns):
device_id       87726 non-null int64
phone_brand     87726 non-null object
device_model    87726 non-null object
dtypes: int64(1), object(2)
memory usage: 2.0+ MB

In [0]:
phone_brand_df.describe()

          device_id
count  8.772600e+04
mean  -5.212557e+15
std    5.330157e+18
min   -9.223322e+18
25%   -4.623331e+18
50%   -3.109802e+16
75%    4.635194e+18
max    9.222849e+18

In [0]:
phone_brand_df.nunique(axis=0) #returns the number of unique values for each variable.

device_id       87726
phone_brand       116
device_model     1467
dtype: int64

In [0]:
phone_brand_df.device_model.unique()

array(['Y13', 'V183', 'R7s', ..., 'Galaxy Tab S T705', 'IVO 8800',
       'U59GT'], dtype=object)

In [0]:
#phone_brand_df.replace(to_replace=['华为','小米','三星', '魅族','酷派','乐视','联想'], value=['Huawei','Xiaomi','Samsung','Meizu','Coolpad','LeEco','Lenovo'], inplace=True)
phone_brand_df.replace(to_replace=['华为','小米','三星', '魅族','酷派','乐视','联想','优米','天语','普耐尔','中国移动','亿通','努比亚','美图','酷比魔方','酷比','锤子'], 
              value=['Huawei','Xiaomi','Samsung','Meizu','Coolpad','LeEco','Lenovo','Quality rice','Amagatarai','Purnell','China Mobile','Yitong','Nubia','Mito',
                     'Cool Rubiks Cube','Cool than','hammer'], 
              inplace=True)

In [0]:
phone_brand_df.device_model.unique()

array(['Y13', 'V183', 'R7s', ..., 'Galaxy Tab S T705', 'IVO 8800',
       'U59GT'], dtype=object)

**Merging Gender & Phone data frame**

In [0]:
phone_gender_combined = pd.merge(gender_age_df, phone_brand_df)
phone_gender_combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 74617 entries, 0 to 74616
Data columns (total 6 columns):
device_id       74617 non-null int64
gender          74617 non-null object
age             74617 non-null int64
group           74617 non-null object
phone_brand     74617 non-null object
device_model    74617 non-null object
dtypes: int64(2), object(4)
memory usage: 4.0+ MB

In [0]:
phone_gender_combined.head()

             device_id gender  age   group phone_brand device_model
0 -8076087639492063270      M   35  M32-38      Xiaomi         MI 2
1 -2897161552818060146      M   35  M32-38      Xiaomi         MI 2
2 -8260683887967679142      M   35  M32-38      Xiaomi         MI 2
3 -4938849341048082022      M   30  M29-31     Samsung    Galaxy S4
4   245133531816851882      M   30  M29-31       SUGAR         时尚手机

In [0]:
sum(pd.isnull(phone_gender_combined['device_id']))

0

In [0]:
phone_gender_combined.nunique(axis=0) #returns the number of unique values for each variable.
#phone_gender_combined.describe().apply(lambda s: s.apply(lambda x: format(x, 'f')))

device_id       74617
gender              2
age                85
group              12
phone_brand       111
device_model     1427
dtype: int64

**Event Data table**

In [0]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
link = 'https://drive.google.com/open?id=1nlZw1xzY3tW8TlKJL18yMCfi3T6Eo9o_' # The shareable link
fluff, id = link.split('=')
print (id) # Verify that you have everything after '='

1nlZw1xzY3tW8TlKJL18yMCfi3T6Eo9o_

In [0]:
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('events_data_file.csv')  
event_data_df = pd.read_csv('events_data_file.csv')
# Dataset is now stored in a Pandas Dataframe

In [0]:
event_data_df.head()

   event_id     device_id            timestamp  ...  latitude   city  state
0       1.0  2.918269e+16  2016-05-01 00:55:25  ...  28.68161  Delhi  Delhi
1    7104.0  2.918269e+16  2016-05-02 09:37:02  ...  28.68161  Delhi  Delhi
2   29661.0  2.918269e+16  2016-05-04 00:56:04  ...  28.68161  Delhi  Delhi
3   33133.0  2.918269e+16  2016-05-06 05:01:15  ...  28.68161  Delhi  Delhi
4   38980.0  2.918269e+16  2016-05-06 09:55:04  ...  28.68161  Delhi  Delhi

[5 rows x 7 columns]

In [0]:
event_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3252950 entries, 0 to 3252949
Data columns (total 7 columns):
event_id     float64
device_id    float64
timestamp    object
longitude    float64
latitude     float64
city         object
state        object
dtypes: float64(4), object(3)
memory usage: 173.7+ MB

In [0]:
event_data_df.describe()

           event_id     device_id     longitude      latitude
count  3.252950e+06  3.252497e+06  3.252527e+06  3.252527e+06
mean   1.626476e+06  1.012200e+17  7.815868e+01  2.168851e+01
std    9.390459e+05  5.316758e+18  4.235570e+00  5.789111e+00
min    1.000000e+00 -9.222957e+18  1.256700e+01  8.190110e+00
25%    8.132382e+05 -4.540611e+18  7.583543e+01  1.780171e+01
50%    1.626476e+06  1.726820e+17  7.726814e+01  2.216454e+01
75%    2.439713e+06  4.861813e+18  8.031916e+01  2.868278e+01
max    3.252950e+06  9.222849e+18  9.545946e+01  4.187190e+01

In [0]:
event_data_df.nunique(axis=0) #returns the number of unique values for each variable.

event_id     3252950
device_id      60865
timestamp     588126
longitude      60095
latitude       60185
city             933
state             32
dtype: int64

In [0]:
sum(pd.isnull(event_data_df['longitude']))

423

In [0]:
sum(pd.isnull(event_data_df['latitude']))

423

In [0]:
sum(pd.isnull(event_data_df['state']))

377

In [0]:
sum(pd.isnull(event_data_df['city']))

0

In [0]:
sum(pd.isnull(event_data_df['device_id']))

453

In [0]:
#Correcting the null values present in 'state' column
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="BhalswaJahangirpur")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="Delhi")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="Deoli")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="DilliCantonment")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="Gokalpur")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="NangloiJat")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="NiDilli")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="RoshanPura")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="SultanpurMajra")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="Tigri")),"Delhi",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="Mumbai")),"Maharashtra",event_data_df['state']) 
event_data_df['state'] = np.where(((event_data_df['state'].isnull()) & (event_data_df['city'] =="Pune")),"Maharashtra",event_data_df['state'])

In [0]:
sum(pd.isnull(event_data_df['state']))

250

In [0]:
#Correcting the null values present in 'longitude' column
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="BhalswaJahangirpur")),"77.247696",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="Delhi")),"77.266049",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="Deoli")),"77.302223",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="DilliCantonment")),"77.217069",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="Gokalpur")),"77.331379",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="NangloiJat")),"77.126448",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="NiDilli")),"77.307839",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="RoshanPura")),"77.08055",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="SultanpurMajra")),"77.10988",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="Tigri")),"77.230918",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="Mumbai")),"72.83738",event_data_df['longitude']) 
event_data_df['longitude'] = np.where(((event_data_df['longitude'].isnull()) & (event_data_df['city'] =="Pune")),"73.859134",event_data_df['longitude'])

In [0]:
sum(pd.isnull(event_data_df['longitude']))

0

In [0]:
#Correcting the null values present in 'latitude' column
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="BhalswaJahangirpur")),"28.787158",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="Delhi")),"28.712135",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="Deoli")),"28.579339",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="DilliCantonment")),"28.639109",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="Gokalpur")),"28.780808",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="NangloiJat")),"28.726816",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="NiDilli")),"28.631404",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="RoshanPura")),"28.646277",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="SultanpurMajra")),"28.799271",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="Tigri")),"28.559426",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="Mumbai")),"18.981604",event_data_df['latitude']) 
event_data_df['latitude'] = np.where(((event_data_df['latitude'].isnull()) & (event_data_df['city'] =="Pune")),"18.575338",event_data_df['latitude'])

In [0]:
sum(pd.isnull(event_data_df['latitude']))

0

In [0]:
event_data_df.nunique(axis=0) #returns the number of unique values for each variable.

event_id     3252950
device_id      60865
timestamp     588126
longitude      60096
latitude       60186
city             933
state             32
dtype: int64

**Now we targeting to particualr state data where we need to figure it out**

In [0]:
#Creating New Data frame for particualr state for which we need to gather info
options = ['AndhraPradesh', 'Pondicherry', 'Mizoram', 'AndamanandNicobarIslands', 'Meghalaya', 'HimachalPradesh'] 
  
# selecting rows based on condition 
#new_event_data_df is only target particualr 6 state that are present in options
new_event_data_df = event_data_df[event_data_df['state'].isin(options)] 

#new_event_data_df = event_data_df.copy()

In [0]:
new_event_data_df.head()

         event_id     device_id  ...           city          state
1868677    5985.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868678   56595.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868679   75863.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868680   81849.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh
1868681   97846.0 -7.971778e+18  ...  Visakhapatnam  AndhraPradesh

[5 rows x 7 columns]

In [0]:
new_event_data_df.nunique(axis=0) #returns the number of unique values for each variable.

event_id     329125
device_id      5223
timestamp    240657
longitude      5204
latitude       5211
city            113
state             6
dtype: int64

In [0]:
# Group By state
df_size_by_state = new_event_data_df.groupby(['state']).size().reset_index()
df_size_by_state.columns.values[1] = 'Count'  # renaming the size column
print(df_size_by_state)

                      state   Count
0  AndamanandNicobarIslands    1515
1             AndhraPradesh  321332
2           HimachalPradesh    1409
3                 Meghalaya    1515
4                   Mizoram    1613
5               Pondicherry    1741

In [0]:
#new_event_data_df.set_option(device_id,'display.float_format', lambda x: '%.5f' % x)
new_event_data_df.info()

# Count for all state : 3252950

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329125 entries, 1868677 to 2197848
Data columns (total 7 columns):
event_id     329125 non-null float64
device_id    329056 non-null float64
timestamp    329125 non-null object
longitude    329125 non-null object
latitude     329125 non-null object
city         329125 non-null object
state        329125 non-null object
dtypes: float64(2), object(5)
memory usage: 20.1+ MB

In [0]:
new_event_data_df.device_id.unique()

array([-7.97177847e+18, -2.45720187e+18, -1.35449895e+18, ...,
       -2.42700765e+18,  1.59138181e+18,  9.71676291e+17])

In [0]:
sum(pd.isnull(new_event_data_df['longitude'])) # Now null count reduce from 423 to 63

0

In [0]:
sum(pd.isnull(new_event_data_df['latitude'])) # Now null count reduce from 423 to 63

0

In [0]:
sum(pd.isnull(new_event_data_df['state'])) # Now null count reduce from 377 to 0 so we can say that we get rid of state null values since we already targeted particualr state

0

In [0]:
sum(pd.isnull(new_event_data_df['device_id'])) # Now we 've find 69 device id have null values which is earlier 453

69

In [0]:
# Getting mode of each column
#new_event_data_df.mode()
new_event_data_df.mode(axis='rows', numeric_only=True)

         event_id     device_id
0          5985.0  3.137054e+18
1          5990.0           NaN
2          5998.0           NaN
3          6000.0           NaN
4          6001.0           NaN
...           ...           ...
329120  3252908.0           NaN
329121  3252913.0           NaN
329122  3252919.0           NaN
329123  3252922.0           NaN
329124  3252943.0           NaN

[329125 rows x 2 columns]

In [0]:
#Filling Null values of device_id with mode of particualr column but it 's not workes so just get rid of by removing
#new_event_data_df['device_id'].fillna(new_event_data_df.device_id.mode())
new_event_data_df.dropna(subset=['device_id'], inplace=True)

In [0]:
sum(pd.isnull(new_event_data_df['device_id']))

0

In [0]:
# try to conver device _id from flot to int
new_event_data_df['device_id'].astype(np.int64)

1868677   -7971778470363550720
1868678   -7971778470363550720
1868679   -7971778470363550720
1868680   -7971778470363550720
1868681   -7971778470363550720
                  ...
2197844    8845073255117719552
2197845   -6371607072742888448
2197846   -2427007648918548992
2197847    1591381814904359680
2197848     971676290699351168
Name: device_id, Length: 329056, dtype: int64

In [0]:
# Group By Device ID
df_size_by_devID = new_event_data_df.groupby(['device_id']).size().reset_index()
df_size_by_devID.columns.values[1] = 'Count'  # renaming the size column
print(df_size_by_devID)

         device_id  Count
0    -9.222173e+18     20
1    -9.215269e+18     53
2    -9.213181e+18      2
3    -9.211311e+18     89
4    -9.206856e+18    156
...            ...    ...
5218  9.216831e+18     44
5219  9.217997e+18      2
5220  9.219480e+18      2
5221  9.219926e+18     40
5222  9.220807e+18     27

[5223 rows x 2 columns]

In [0]:
profile_new_event_data_df = pandas_profiling.ProfileReport(new_event_data_df)
#profile.to_file(outputfile="Capstone1_preprocessing.html")
profile_new_event_data_df

**Checking How many device Id Present in event datat not in (Phone & gender)**

In [0]:
mergedStuff = pd.merge(phone_gender_combined, new_event_data_df, on=['device_id'], how='inner')
mergedStuff.head()
mergedStuff.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 669 entries, 0 to 668
Data columns (total 12 columns):
device_id       669 non-null int64
gender          669 non-null object
age             669 non-null int64
group           669 non-null object
phone_brand     669 non-null object
device_model    669 non-null object
event_id        669 non-null float64
timestamp       669 non-null object
longitude       669 non-null object
latitude        669 non-null object
city            669 non-null object
state           669 non-null object
dtypes: float64(1), int64(2), object(9)
memory usage: 67.9+ KB

In [0]:
# Read in first 10 lines of surveys table
survey_sub = phone_gender_combined.head(10)
species_sub=new_event_data_df.head(10)
#merged_inner = pd.merge(right=survey_sub, left=species_sub, left_on='device_id', right_on='device_id')
merged_inner = pd.merge(survey_sub, species_sub, on='device_id', how='right')
merged_inner.shape
merged_inner
merged_inner.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 0 to 9
Data columns (total 12 columns):
device_id       10 non-null float64
gender          0 non-null object
age             0 non-null float64
group           0 non-null object
phone_brand     0 non-null object
device_model    0 non-null object
event_id        10 non-null float64
timestamp       10 non-null object
longitude       10 non-null object
latitude        10 non-null object
city            10 non-null object
state           10 non-null object
dtypes: float64(3), object(9)
memory usage: 1.0+ KB

In [0]:
sum(pd.isnull(merged_inner['phone_brand']))

10

In [0]:
merged_inner.nunique(axis=0)#returns the number of unique values for each variable.

device_id        1
gender           0
age              0
group            0
phone_brand      0
device_model     0
event_id        10
timestamp       10
longitude        1
latitude         1
city             1
state            1
dtype: int64

**Now we are trying to merge New dataframe with phone & age brand with condtion**

In [0]:
dfnew_state = pd.merge(phone_gender_combined, new_event_data_df, on='device_id', how='right') #Right Join on device_id ( phone & gender on left & event data frame on right)
# dfnew = pd.merge(phone_gender_combined, event_data_df, on='device_id', how='inner') #Inner Join on device_id ( phone & gender on left & event data frame on right)
dfnew_state.info()
dfnew_state.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329056 entries, 0 to 329055
Data columns (total 12 columns):
device_id       329056 non-null int64
gender          669 non-null object
age             669 non-null float64
group           669 non-null object
phone_brand     669 non-null object
device_model    669 non-null object
event_id        329056 non-null float64
timestamp       329056 non-null object
longitude       329056 non-null object
latitude        329056 non-null object
city            329056 non-null object
state           329056 non-null object
dtypes: float64(2), int64(1), object(9)
memory usage: 32.6+ MB

          device_id gender  ...           city          state
0 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
1 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
2 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
3 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
4 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh

[5 rows x 12 columns]

In [0]:
#Phone brand null count in new dataframe
sum(pd.isnull(dfnew_state['phone_brand']))

328387

In [0]:
dfnew_state.nunique(axis=0)#returns the number of unique values for each variable.

device_id         5223
gender               2
age                 16
group               11
phone_brand          7
device_model        27
event_id        329056
timestamp       240626
longitude         5204
latitude          5211
city               113
state                6
dtype: int64

**Now we are trying to merge New dataframe with phone & age brand without condtion  df4 dataframe**

In [0]:
df4 = pd.merge(phone_gender_combined, new_event_data_df)
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 669 entries, 0 to 668
Data columns (total 12 columns):
device_id       669 non-null int64
gender          669 non-null object
age             669 non-null int64
group           669 non-null object
phone_brand     669 non-null object
device_model    669 non-null object
event_id        669 non-null float64
timestamp       669 non-null object
longitude       669 non-null object
latitude        669 non-null object
city            669 non-null object
state           669 non-null object
dtypes: float64(1), int64(2), object(9)
memory usage: 67.9+ KB

In [0]:
df4.head()

          device_id gender  ...           city          state
0 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
1 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
2 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
3 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh
4 -6552729385743211      M  ...  Rajendranagar  AndhraPradesh

[5 rows x 12 columns]

In [0]:
df4.describe()

          device_id         age      event_id
count  6.690000e+02  669.000000  6.690000e+02
mean  -2.330344e+17   32.544096  1.595214e+06
std    1.176516e+18    9.763517  9.390091e+05
min   -6.289140e+18   21.000000  6.984000e+03
25%   -1.180229e+18   27.000000  7.696080e+05
50%   -2.849262e+16   32.000000  1.593593e+06
75%   -1.364213e+15   38.000000  2.366475e+06
max    4.184872e+18   79.000000  3.249410e+06

In [0]:
df4.nunique(axis=0)#returns the number of unique values for each variable.

device_id        28
gender            2
age              16
group            11
phone_brand       7
device_model     27
event_id        669
timestamp       659
longitude        28
latitude         28
city             20
state             1
dtype: int64

In [0]:
#Phone brand no null count in new dataframe
sum(pd.isnull(df4['phone_brand']))

0

In [0]:
#device_model no null count in new dataframe
sum(pd.isnull(df4['device_model']))

0

In [0]:
df4.device_id.unique()

array([   -6552729385743211,  -258158835257519424, -1328789920050419200,
           8492297012485123,   105387424403700736,  -594711597881402752,
        1697086779705292288, -1180228997135426560, -1531639076514616064,
          -1364213210730105,   333494090404734400,  1138187655496362624,
          29487598347576048,  4184872012668940800,   -23366031018699840,
       -1438495210756671488,  2111248373247544064, -6289140063501067264,
        -279317695185245376,   419885172081269696,   700156737670276608,
       -4647981010574665728,  1910762255583389952,   -28492619212284472,
         -34779641846092840,  -548549229804626560,   205679329653904000,
       -1870074800027757568])

**Now we are trying to merge event dataframe with phone & age brand with condtion dfnew dataframe**

In [0]:
dfnew = pd.merge(phone_gender_combined, event_data_df, on='device_id', how='right') #Right Join on device_id ( phone & gender on left & event data frame on right)
# dfnew = pd.merge(phone_gender_combined, event_data_df, on='device_id', how='inner') #Inner Join on device_id ( phone & gender on left & event data frame on right)
dfnew.head()

      device_id gender   age  ...            latitude           city          state
0 -6.552729e+15      M  28.0  ...  17.338946999999994  Rajendranagar  AndhraPradesh
1 -6.552729e+15      M  28.0  ...  17.338946999999994  Rajendranagar  AndhraPradesh
2 -6.552729e+15      M  28.0  ...  17.338946999999994  Rajendranagar  AndhraPradesh
3 -6.552729e+15      M  28.0  ...  17.338946999999994  Rajendranagar  AndhraPradesh
4 -6.552729e+15      M  28.0  ...  17.338946999999994  Rajendranagar  AndhraPradesh

[5 rows x 12 columns]

In [0]:
# Inner Join count : 14290 
# Right Join count : 3252950
# Left Join Count  : 88566 
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3252950 entries, 0 to 3252949
Data columns (total 12 columns):
device_id       float64
gender          object
age             float64
group           object
phone_brand     object
device_model    object
event_id        float64
timestamp       object
longitude       object
latitude        object
city            object
state           object
dtypes: float64(3), object(9)
memory usage: 322.6+ MB

In [0]:
dfnew.nunique(axis=0)#returns the number of unique values for each variable.

device_id         60865
gender                2
age                  50
group                12
phone_brand          21
device_model        168
event_id        3252950
timestamp        588126
longitude         60096
latitude          60186
city                933
state                32
dtype: int64

In [0]:
#Phone brand null count in new dataframe
sum(pd.isnull(dfnew['phone_brand']))

3238660

**dfnew dataframe Profiling**

In [0]:
profile = pandas_profiling.ProfileReport(dfnew)
profile.to_file(outputfile="Capstone1_preprocessing.html")

In [0]:
profile

In [0]:
dfnew.phone_brand.value_counts()

Samsung             4424
Xiaomi              3585
Huawei              1973
vivo                1045
OPPO                 874
Meizu                758
Coolpad              647
HTC                  336
LeEco                240
Quality rice         194
Amagatarai            92
Purnell               40
China Mobile          21
Yitong                17
Mito                  13
Nubia                 13
Cool Rubiks Cube       8
联想                     4
LG                     3
Cool than              2
hammer                 1
Name: phone_brand, dtype: int64

In [0]:
#Correaltion b/w all data
# Create correlation matrix
corr_matrix = dfnew.corr().abs()
corr_matrix

           device_id       age  event_id
device_id   1.000000  0.030163  0.000655
age         0.030163  1.000000  0.007682
event_id    0.000655  0.007682  1.000000

In [0]:
dfnew.groupby('phone_brand')['group'].nunique().plot(kind='bar',figsize = (10, 10))
plt.show()

In [0]:
dfnew.groupby(['phone_brand','group']).size().unstack().plot(kind='bar',stacked=True,figsize = (20, 10),legend='true')
plt.show()

In [0]:
dfnew.groupby(['phone_brand','city']).size().unstack().plot(kind='bar',stacked=True,figsize = (20, 10),legend='true')
plt.show()

In [0]:
dfnew.groupby(['group','city']).size().unstack().plot(kind='bar',stacked=True,figsize = (20, 10),legend='true')
plt.show()

In [0]:
space = np.ones(21)/20
dfnew['phone_brand'].value_counts().plot(kind='pie',fontsize=14, explode=space, startangle=160, figsize=(11,11), legend=True ,autopct='%3.1f%%',
                                         wedgeprops=dict(width=0.15))

In [0]:
dfnew['state'].value_counts().plot.bar(figsize=(10,5))
plt.xlabel('state')
plt.ylabel('device_id')
plt.title('Statewise distribution of device_ids')

Text(0.5, 1, 'Statewise distribution of device_ids')

**Map realted code**

In [0]:
import folium
from folium import plugins  
latitude = 37.0902
longitude = -95.7129

#m = folium.Map([17.338947, 78.487472], zoom_start=5,width=500,height=500)
traffic_map = folium.Map(location=[latitude, longitude], zoom_start=5)
#stationArr = dfnew[['latitude', 'longitude']].as_matrix()

# plot heatmap
#m.add_children(plugins.HeatMap(stationArr, radius=15))
traffic_map

In [0]:
locations = dfnew_state[['latitude', 'longitude']]
locationlist = locations.values.tolist()
len(locationlist)
locationlist[7]

['17.338946999999994', '78.487472']

In [0]:
len(locationlist)

329056

In [0]:
import sys
sys.setrecursionlimit(329056)

In [0]:
sys.getrecursionlimit()

329056

In [0]:
map = folium.Map(location=[17.338946999999994, 78.487472], zoom_start=12)
for point in range(10000, len(locationlist)):
    folium.Marker(locationlist[point], popup=dfnew_state['event_id'][point]).add_to(map)
map

NameError: ignored